# basic options
title: Rocio Krebs GitBook
author: Rocio Krebs
email: rociokrebs@outlook.com
description: A wonderful site
github_username:  rokrebs

# Build settings
markdown: kramdown
theme: minima
